export const lojasConstantes = {
  CARREGAR_BUSCAS_LOJAS: "CARREGAR_BUSCAS_LOJAS",
  CARREGAR_MANUTENCAO_LOJAS: "CARREGAR_MANUTENCAO_LOJAS",
  BUSCAR_LOJAS: "BUSCAR_LOJAS",
  SALVAR_LOJAS: "SALVAR_LOJAS",
  APAGAR_LOJAS: "APAGAR_LOJAS",
  ADICIONAR_PRODUTO_LOJA: "ADICIONAR_PRODUTO_LOJA",
  REMOVER_PRODUTO_LOJA: "ADICIONAR_PRODUTO_LOJA",
  CARREGAR_LISTAGEM_PRODUTOS: "CARREGAR_LISTAGEM_PRODUTOS",
  SELECIONAR_PRODUTO: "SELECIONAR_PRODUTO", 
  ATUALIZAR_ATRIBUTOS: "ATUALIZAR_ATRIBUTOS",
};
