export const lojasConstantes = {
  CARREGAR_BUSCAS_LOJAS: "CARREGAR_BUSCAS_LOJAS",
  CARREGAR_MANUTENCAO_LOJAS: "CARREGAR_MANUTENCAO_LOJAS",
  BUSCAR_LOJAS: "BUSCAR_LOJAS",
  SALVAR_LOJAS: "SALVAR_LOJAS",
  APAGAR_LOJAS: "APAGAR_LOJAS"
};
