export const produtosConstantes = {
    CARREGAR_BUSCAS_PRODUTO: "CARREGAR_BUSCAS_PRODUTO",
    CARREGAR_MANUTENCAO_PRODUTO: "CARREGAR_MANUTENCAO_PRODUTO",
    BUSCAR_PRODUTOS: "BUSCAR_PRODUTOS",
    SALVAR_PRODUTOS: "SALVAR_PRODUTOS",
    APAGAR_PRODUTOS: "APAGAR_PRODUTOS"
}