export const produtosConstantes = {
    CARREGAR_BUSCAS_PRODUTOS: "CARREGAR_BUSCAS_PRODUTOS",
    CARREGAR_MANUTENCAO_PRODUTOS: "CARREGAR_MANUTENCAO_PRODUTOS",
    BUSCAR_PRODUTOS: "BUSCAR_PRODUTOS",
    SALVAR_PRODUTOS: "SALVAR_PRODUTOS",
    APAGAR_PRODUTOS: "APAGAR_PRODUTOS"
}